Add minutes from Community Call on 2022-12-08
SovereignCloudStack/minutes pull request #119
Opened 2022-12-08 14:58 UTC by itrich

Signed-off-by: Eduard Itrich <eduard@itrich.net>

2022-12-08 14:58 UTC, itrich commented
I'll proof-read this once again and then open the PR for reviews

2022-12-08 16:15 UTC, garloff requested changes
Please perform the minor corrections! TIA!

2022-12-08 16:15 UTC, garloff commented on community-call/20221208.md
> +* Wiping data from local disks needs work (currently lvremove is insufficient!)
better: (currently used lvremove is insufficient)

2022-12-08 16:15 UTC, garloff commented on community-call/20221208.md
> +* Tests should be added to a test collection
This and the next bullet should have an additional indentation (they are sub items to the loadbalancer behavior). Also beahvior -> behavior.

2022-12-08 16:15 UTC, garloff commented on community-call/20221208.md
> +* PoC works, yeah!
This and the next one: Additional indentation (they are subitems to device auth grant)

2022-12-08 16:15 UTC, garloff commented on community-call/20221208.md
> +Discussion on deploying a k8s cluster on top of the management plane that can host additional applications/services. Everybody agreed that this is a good idea. Additional discussion on how this can b
s/minio/minikube/

2022-12-08 16:15 UTC, garloff commented on community-call/20221208.md
> +* gx-scs has been cleaned up and will be hoepfully be available again next week.
s/hoep/hope/

2022-12-08 18:46 UTC, fkr commented
I actually wonder why we duplicate the contents of the minutes of each team call. Imho it should suffice to point to the minutes from that call for the technical stuff that is being reported.
Why am I suggesting that: Because I want people to actually read the original minutes of the team call and to me this seems duplicate effort with the danger of actually not being as complete as the team call minutes.

Furthermore we agreed a while back (at least @berendt and I suggested that) that we don't do the participants tracking for the community call.

2022-12-19 06:44 UTC, itrich commented
> I actually wonder why we duplicate the contents of the minutes of each team call. Imho it should suffice to point to the minutes from that call for the technical stuff that is being reported. Why am I suggesting that: Because I want people to actually read the original minutes of the team call and to me this seems duplicate effort with the danger of actually not being as complete as the team call minutes.

I followed the minutes recorded during earlier calls without any further intention. Just providing the link to the corresponding minutes will drastically reduce the  difficulty to take minutes. On the other hand, providing a short summary of the most important hightlights offers readers the opportunity to grasp what is happening without having to dig through secondary documents. (Which is what we should strive for IMHO). I'd propose to keep the summary if the minute taker is willing to record one.

> Furthermore we agreed a while back (at least @berendt and I suggested that) that we don't do the participants tracking for the community call.

You're right. I removed the participants' list from the minutes.

2023-01-09 14:05 UTC, itrich commented
@garloff I processed your comments and IMHO this PR can be reviewed again.

2023-01-18 15:27 UTC, garloff approved these changes

2023-01-18 15:28 UTC, merged