add: SIG iam 20230127
SovereignCloudStack/minutes pull request #166
Opened 2023-01-27 16:30 UTC by reqa

Signed-off-by: Arvid Requate <requate@univention.de>

2023-01-27 20:57 UTC, JuanPTM commented on sig-iam/20230127.md
> +    * * @garloff
Small error.
```suggestion
    * @garloff
```

2023-01-27 20:59 UTC, JuanPTM requested changes
Only a duplicated `*` rest look good to me.

2023-01-30 17:57 UTC, JuanPTM approved these changes

2023-01-30 17:57 UTC, JuanPTM commented
LGTM

2023-01-30 21:54 UTC, fkr approved these changes

2023-01-30 21:54 UTC, merged