add minutes from the overflow slot
SovereignCloudStack/minutes pull request #191
Opened 2023-02-22 17:10 UTC by matfechner

2023-02-22 17:49 UTC, berendt commented
@matfechner Can you please add me to the list of attendees

2023-02-22 17:57 UTC, ppkuschy requested changes
Pls see suggestion

2023-02-22 17:57 UTC, ppkuschy commented on iaas/20230220.md
> +
```suggestion
* @berendt 
```
@berendt Wants to be added as attendee

2023-02-23 22:02 UTC, fkr approved these changes
LGTM!

2023-02-24 06:45 UTC, ppkuschy approved these changes

2023-02-24 06:55 UTC, merged