Add OPS call minutes from 2024/04/04
SovereignCloudStack/minutes pull request #503
Opened 2024-04-04 07:56 UTC by matofeder

2024-04-05 14:34 UTC, bitkeks requested changes

2024-04-05 18:17 UTC, fkr commented on ops/20240404.md
> +- Report in the community call will be done by: @
```suggestion
- Report in the community call will be done by: @bitkeks 
```

2024-04-05 18:17 UTC, fkr approved these changes
LGTM once the noted addition from @bitkeks is included

2024-04-08 09:23 UTC, matofeder commented on ops/20240404.md
> +- Report in the community call will be done by: @
fixed: 52bbb0f85cd49cfef07c1b8d861e82fd615e4438

2024-04-09 08:00 UTC, bitkeks approved these changes

2024-04-09 08:00 UTC, merged