Ops-IAM Meeting minutes 20220922
SovereignCloudStack/minutes pull request #56
Opened 2022-09-22 13:02 UTC by o-otte

Signed-off-by: Oliver Otte <otte@gonicus.de>

2022-09-22 13:43 UTC, fkr commented on ops-iam/20220922.md
> +*@o-otte
please fix formatting

2022-09-22 13:43 UTC, fkr requested changes
see inline comment. thanks @o-otte!

2022-09-22 13:49 UTC, o-otte commented on ops-iam/20220922.md
> +*@o-otte
Fixed with [a33d95e](https://github.com/SovereignCloudStack/minutes/pull/56/commits/a33d95ec2b4ef831041b3be04a82ffa6f38c1601)

2022-09-23 06:46 UTC, fkr approved these changes
awesome. thanks @o-otte!

2022-09-23 06:46 UTC, merged