Add minutes of 20221114 container meeting
SovereignCloudStack/minutes pull request #96
Opened 2022-11-14 11:06 UTC by joshmue

Signed-off-by: Joshua Mühlfort <muehlfort@gonicus.de>

2022-11-14 17:30 UTC, garloff requested changes

2022-11-14 17:30 UTC, garloff commented on container/20221114.md
> +* Conformance test framework discussion. Two different main scenarios:
I think I ended up with three different test scenarios:
1. Conformance tests for SCS REST API (Cluster Lifecycle Management)
2. Conformance tests for Cluster Properties (Assume cluster already exists and we have cluster-admin access)
3. Implementation-specific tests (unit tests / integration tests), which may assume CAPI (in our ref. impl.)

2022-11-14 17:30 UTC, garloff commented on container/20221114.md
> +         * https://github.com/kubernetes-sigs/cluster-api/blob/fa70f61a77828cea2d5d059ffd0dfcf6bcbc9f2d/test/e2e/k8s_conformance.go#L109
As far as *SCS conformance* tests are concerned, we can not assume that the implementation uses CAPI.
(That said, the tests that are part of the CAPI tests may not make that assumption everywhere ... at least some comment from Janis indicated so.)

2022-11-15 08:15 UTC, joshmue commented on container/20221114.md
> +* Conformance test framework discussion. Two different main scenarios:
I took your new bullet points into the minutes directly :+1:

2022-11-15 08:16 UTC, joshmue commented on container/20221114.md
> +         * https://github.com/kubernetes-sigs/cluster-api/blob/fa70f61a77828cea2d5d059ffd0dfcf6bcbc9f2d/test/e2e/k8s_conformance.go#L109
Moved that part to the new 3rd scenario.

2022-12-08 15:44 UTC, garloff approved these changes
Thanks, let's merge this!

2022-12-08 15:45 UTC, merged